### ISSUE TITLE
missing map on venue page

### ISSUE THREAD

**Issue by codersquid** [pydata/conf_site#12]
We want to embed a google map iframe in the venue page, and the venue page is a cms page.

markdown renders html, but iframe elements are being ignored.

either we figure out how to handle that, or switch to using a template for the venue page.

**Comment by furiousdave** [comment]
The project was using a markdown parser supplied by symposion, 
MARKITUP_FILTER = ["symposion.markdown_parser.parse", {}]

That parse function utilizes html5lib to sanitize the code which, by default, escapes iframes for security reasons. I ended up adding our own markdown_parser.py into this project in order to extend the sanitizer and add iframe support.

https://github.com/pydata/conf_site/commit/6d7eadb66146ed8b4d21c3ab0956a1fcfc4c85d3

**Comment by codersquid** [comment]
thanks! looks good.
