### ISSUE TITLE
Speaker notifications have to be sent 5 at a time (CRITICAL)

### ISSUE THREAD

**Issue by Dr-G** [pydata/conf_site#179]
We currently have to click only five submissions at a time to receive accept/reject notifications, or risk the notification emails not sending. This needs to be a one-click process.

**Comment by martey** [comment]
I haven't seen any error messages associated with this and symposion uses `[send_mass_mail](https://docs.djangoproject.com/en/1.9/topics/email/#send-mass-mail)` instead of `[send_mail](https://docs.djangoproject.com/en/1.9/topics/email/#send-mail)` (so only one connection , so I assume it is occurring within the Google Apps SMTP server that we are currently using.

If this is correct, the issue should be able to be resolved by switching to an external email service provider. We've talked about using [Mailgun](https://www.mailgun.com/) in the past, since it is integrated with Rackspace. Another alternative would be to become a subuser on my [SendGrid](https://sendgrid.com/) account.

Mailgun requires a credit card to actually send mail, and both services will require DNS changes to pydata.org, so I will need some assistance to implement this.

**Comment by aterrel** [comment]
I agree with martey this sounds like an issue with the smtp server
rejecting suspected spam.

I would vote for using SendGrid. I can set up an account for numfocus.

-- Andy
