### ISSUE TITLE
Event sites should not need a whole new branch (HIGH)

### ISSUE THREAD

**Issue by Dr-G** [pydata/conf_site#182]
“Event” should be a concept in the data model
Sponsor levels and benefits have to be re-created for every single site
Sponsor benefits don’t appear until you “save” a sponsor
Admin logins have to be re-created for every single site

**Comment by martey** [comment]
I think this issue is less about the fact that some conference sites use branches of the codebase to activate additional features (e.g. the [impressum in the Berlin 2017's site footer](https://github.com/pydata/conf_site/commit/33b9c18a3d240b8aefff1ef6f6a2f6163a5e0704), the ["poster session" proposal type in the San Luis 2017 site](https://github.com/pydata/conf_site/commit/27cc8d6c0eb57455d2410e0a3c637dd881218dcb)), and more about the fact that each conference site is its own distinct website, hosted on its own server, with its own separate database.

Symposion has the ability to store multiple conferences in the same database, but the impression I received when I started was that this ended up causing more issues than it solved. I can do some testing to see if this is not the case, and whether hosting all conference sites on one server (and in one database) is feasible.

**Comment by aterrel** [comment]
Well a initialization script can fix several things like the sponsor levels
and benefits being re-created.

**Comment by martey** [comment]
The sponsor benefits and levels should already be initialized when each conference site is created. [sponsor_benefits.json](https://github.com/pydata/conf_site/blob/cc65bb91054cd0778663bab955baae728d1653a1/fixtures/sponsor_benefits.json) and [sponsor_levels.json](https://github.com/pydata/conf_site/blob/cc65bb91054cd0778663bab955baae728d1653a1/fixtures/sponsor_levels.json) contain information about benefits and levels. While [these fixtures need to be loaded into the database manually](https://github.com/pydata/conf_site/blob/95dea5f3c3bae9efe6bb25cd4615b4a823ff876f/docs/source/deployment.rst#customization), I think I have applied them to every conference site, since not applying them causes a variety of other serious problems.

Can it be confirmed that the benefits/levels issue is related to the two types not appearing in the Django admin on conference sites? If so, has this affected every conference site in this cycle, or just some of them?

**Comment by martey** [comment]
I think most of the items mentioned in this issue have been resolved (especially with the merge of #244, which automated data fixture importing). Still outstanding is `“Event” should be a concept in the data model`, but I think symposion's permissions structure is convoluted enough that this will cause more problems than it will solve (e.g. reviewing permissions are site-wide, so a reviewer for one conference would have access to all others by default).
