### ISSUE TITLE
Logo animation (HIGH)

### ISSUE THREAD

**Issue by Dr-G** [pydata/conf_site#184]
There's supposed to be an animation for the PyData logo and it's not happening.

**Comment by martey** [comment]
Is this referring to the parallax scrolling that previously appeared over the image at the top of the homepage (see screenshot)?
![screenshot from 2017-05-17 18-03-40](https://cloud.githubusercontent.com/assets/49076/26178242/2e9a8b98-3b2b-11e7-8f70-0e2c3366b9ea.png)

If so, this was removed in order to fix an issue with dropdown menus (see #167). When a dropdown menu overlapped with the PyData logo in the center of the parallax scrolling and background image, it wasn't possible to click on those overlapping menu items.

I wasn't able to find a way to get the existing parallax scrolling code to work with the site's dropdown menus when I worked on this last month, but I can look to see if there is a different way to do parallax scrolling that won't cause this issue.
