### ISSUE TITLE
Make tables mobile friendly

### ISSUE THREAD

**Issue by RayBB** [pydata/conf_site#416]
Right now the tables on the scheduler are not mobile friendly.

We should make them mobile friendly so that attendees can see the schedule on their phone easily.

I see that the website is currently made with bootstrap 3.3 so we could use the bootstrap responsive tables.
https://getbootstrap.com/docs/3.4/css/#tables-responsive

Would be happy to help do this but don't see any guidelines for contributing.

Example: 
![Screen Shot 2019-11-05 at 17 59 52](https://user-images.githubusercontent.com/921217/68253537-250a9900-fff6-11e9-84ae-529082306d00.png)

**Comment by RayBB** [comment]
Simple fix is to wrap the table in `<div class="table-responsive"></div>`
Then add the following CSS:
```
td {
    white-space: nowrap;
}
table {
    table-layout: auto;
}
```

Result: 
![Screen Shot 2019-11-05 at 18 37 01](https://user-images.githubusercontent.com/921217/68255476-4f128a00-fffb-11e9-90a1-813921035f12.png)

Note: Could also make the table head sticky so it's easier to scroll down like so:
https://stackoverflow.com/questions/21168521/table-fixed-header-and-scrollable-body

**Comment by martey** [comment]
I think the primary mobile usability issue (the inability to read individual presentation titles because the table cells are too small) can be fixed by removing the [`table-layout: fixed` style in `table.calendar`](https://github.com/pydata/conf_site/blob/ec0aff84cbfc14538cb3fc12ad7a18f184da6296/conf_site/static/css/mainstream-vc.css#L734).

I think more aggressive changes should be made in the future in conjunction with an upgrade to Bootstrap 4.
