### ISSUE TITLE
Add Dato logo to landing page

### ISSUE THREAD

**Issue by codersquid** [pydata/conf_site#42]
Dato's logo should be added to the landing page. I've got the logo from Leah, and it's in a branch. I don't know what size etc would make sense for the page.

https://github.com/pydata/conf_site/commit/7069f972ab2449735c38154898a75989f96567ba

**Comment by lsilen** [comment]
I think for the landing page maybe just a little smaller than Continuum’s. Since there isn’t any text to differentiate levels, it’s more of a list of sponsors in general at this time. We put Microsoft and Continuum up in hopes we would have the site up by the time others came on board.

> On Apr 13, 2015, at 10:28 AM, Sheila Miguez <notifications@github.com> wrote:
> 
> Dato's logo should be added to the landing page. I've got the logo from Leah, and it's in a branch. I don't know what size etc would make sense for the page.
> 
> 7069f97 <https://github.com/pydata/conf_site/commit/7069f972ab2449735c38154898a75989f96567ba>
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/42>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449

**Comment by furiousdave** [comment]
I adjusted the size and position slightly and pulled onto the new server.
